# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

environment:
  global:
    nodejs_version: 10
  matrix:
    - TARGET_ARCH: x64
    - TARGET_ARCH: x86

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --build-from-source
  - pip install -r requirements.txt

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

deploy_script:
  - scripts\prebuild-publish.bat
